enable compatibility with pandas v1.0 (#324)
* enable pandas 1.0

* replace `labels` by `codes`

* use proper indexing to not set value on copy of slice

* add dtype to silence future-deprecation warning

* switch from `warnings` to `logger.warning` for consistency

* add to release notes

* more switching from `warnings` to `logger.warning` for consistency

* regenerate all expected figs for plotting tests with pandas 1.0

* appease stickler

* switch to py3.7 for testing on Appveyor (Windows)


> E   AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'